apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-z83y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-z83y
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-z83y
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-z83y
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-z83y
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ijgr-tenant/status-quarkus-io/statusquarkusio-z83y@sha256:7cf02b25449d3e89d0bd12b6c39b261b68258a1ed998a53032b254fa0ed85ff2
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
